# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PADC-9-WPA-IOS-Firebase-Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PADC-9-WPA-IOS-Firebase-Assignment
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Cosmos'
pod 'MaterialComponents/Buttons'

end
